network_name: "calibration"
symbol: "fil"
node_url: "wss://node-fil-calibration-stable.zondax.ch/rpc/v1"
node_token: ""

s3_access_key: OU1AWNEJ7WDXM887FATQ
s3_bucket: beryx-fil
s3_raw_data_path: trace-calibration
s3_secret_key: 2FkrdSbU8t0WaiSo2CtYeDXqFga21Qo0WHg66Wf2
s3_ssl: true
s3_url: s3.ceph-zur1.data.zondax.xyz
s3_service: s5