name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Build
        run: |
          make build
        env:
          TOKEN: ${{ secrets.PECORINO_READ_TOKEN }}

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: ModTidy check
        run: make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint