name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: zondax-runners
    container:
      image: golang:1.23.7
      options: --tty
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'
      - name: Build
        run: |
          git config --global --add safe.directory "*"
          make build
        env:
          TOKEN: ${{ secrets.PECORINO_READ_TOKEN }}

  checks:
    runs-on: zondax-runners
    container:
      image: golang:1.23.7
      options: --tty
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'
      - name: ModTidy check
        run: |
          git config --global --add safe.directory "*"
          make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint

  tests:
    runs-on: zondax-runners
    container:
      image: golang:1.23.7
      options: --tty
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential wget curl gettext-base jq git
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
      - name: Execute dev_env_start_as_daemon from Makefile
        run: |
          make dev_env_start_as_daemon
      - name: test
        run: |
          git config --global --add safe.directory "*"
          make test
