name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: zondax-runners
    container:
      image: golang:1.21
      options: --tty
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Build
        run: |
          git config --global --add safe.directory "*"
          make build
        env:
          TOKEN: ${{ secrets.PECORINO_READ_TOKEN }}

  checks:
    runs-on: zondax-runners
    container:
      image: golang:1.21
      options: --tty
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: ModTidy check
        run: |
          git config --global --add safe.directory "*"
          make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint

  tests:
    runs-on: zondax-runners
    container:
      image: golang:1.21
      options: --tty
    timeout-minutes: 50
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: test
        run: |
          git config --global --add safe.directory "*"
          make test
