name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOPRIVATE: "github.com/zondax/znats"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PECORINO_READ_TOKEN }}
        run: git config --global url."https://zondax:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build
        run: |
          make build

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: ModTidy check
        run: make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: test
        run: make test
